import os
import tempfile
from pathlib import Path
from typing import Any

from griptape_nodes.exe_types.core_types import Parameter, ParameterMode
from griptape_nodes.exe_types.node_types import BaseNode, DataNode
from griptape_nodes.exe_types.param_types.parameter_bool import ParameterBool
from griptape_nodes.exe_types.param_types.parameter_string import ParameterString
from griptape_nodes.retained_mode.griptape_nodes import GriptapeNodes
from griptape_nodes.traits.file_system_picker import FileSystemPicker


class TempFilename(DataNode):
    """Generate a temporary filename.

    Creates a unique temporary filename using Python's tempfile module.
    Works cross-platform (Windows, macOS, Linux).
    """

    def __init__(
        self,
        name: str,
        metadata: dict[Any, Any] | None = None,
    ) -> None:
        super().__init__(name, metadata)

        # Add input parameter for optional directory
        self.directory_input = ParameterString(
            name="directory",
            default_value="",
            tooltip="Optional directory where the temporary file should be created. If empty, uses system temp directory.",
            placeholder_text="Example: /tmp or C:\\Temp",
        )
        self.directory_input.add_trait(
            FileSystemPicker(
                allow_files=False,
                allow_directories=True,
                multiple=False,
            )
        )
        self.add_parameter(self.directory_input)

        # Add input parameter for optional prefix
        self.add_parameter(
            ParameterString(
                name="prefix",
                default_value="",
                tooltip="Optional prefix to prepend to the filename (e.g., 'temp_' or 'tmp_').",
                placeholder_text="Example: temp_ or tmp_",
            )
        )

        # Add input parameter for optional name/text
        self.add_parameter(
            ParameterString(
                name="name",
                default_value="",
                tooltip="Optional custom text to include in the filename. This will be inserted between the prefix and the random part generated by the system.",
                placeholder_text="Example: myfile or document",
            )
        )

        # Add input parameter for name separator
        self.add_parameter(
            ParameterString(
                name="separator",
                default_value="_",
                tooltip="Separator character(s) to use between prefix, name, and the random part. Default is '_'.",
                placeholder_text="Example: _ or -",
            )
        )

        # Add input parameter for optional suffix
        self.add_parameter(
            ParameterString(
                name="suffix",
                default_value="",
                tooltip="Optional suffix to append to the filename (e.g., '_backup' or '.old'). If extension is provided, suffix is appended after extension.",
                placeholder_text="Example: _backup or .old",
            )
        )

        # Add input parameter for optional extension
        self.add_parameter(
            ParameterString(
                name="extension",
                default_value="",
                tooltip="Optional file extension to append to the filename (with or without leading dot, e.g., 'txt' or '.txt').",
                placeholder_text="Example: txt or .txt",
            )
        )

        # Add option to return absolute path or just filename
        self.add_parameter(
            ParameterBool(
                name="return_absolute_path",
                default_value=True,
                tooltip="If True, returns the absolute path. If False, returns just the filename.",
            )
        )

        # Add output parameter for the temporary filename/path
        self.add_parameter(
            ParameterString(
                name="filename",
                allowed_modes={ParameterMode.OUTPUT},
                placeholder_text="The generated temporary filename or path.",
                tooltip="The generated temporary filename or absolute path.",
            )
        )

    def _clean_and_validate_directory(self, directory: str | None) -> str | None:
        """Clean and validate directory path.

        Args:
            directory: Directory path string or None

        Returns:
            Cleaned directory path or None, or error message string
        """
        if not directory:
            return None

        cleaned_dir = GriptapeNodes.OSManager().sanitize_path_string(str(directory))
        cleaned_dir = str(cleaned_dir).strip()

        if not cleaned_dir:
            return None

        dir_path = Path(cleaned_dir)
        if not dir_path.exists():
            return f"Error: {self.name} - Directory does not exist: {cleaned_dir}"

        if not dir_path.is_dir():
            return f"Error: {self.name} - Path is not a directory: {cleaned_dir}"

        return cleaned_dir

    def _clean_string_parameter(self, value: Any) -> str:
        """Clean a string parameter value.

        Args:
            value: Parameter value that may be a string or other type

        Returns:
            Cleaned string value, or empty string if invalid
        """
        if not value:
            return ""

        cleaned = GriptapeNodes.OSManager().sanitize_path_string(str(value))
        cleaned = str(cleaned).strip()

        return cleaned

    def _normalize_extension(self, extension: str) -> str:
        """Normalize extension to ensure it starts with a dot.

        Args:
            extension: Extension string with or without leading dot

        Returns:
            Normalized extension with leading dot
        """
        if not extension:
            return ""

        cleaned = self._clean_string_parameter(extension)
        if not cleaned:
            return ""

        # Ensure extension starts with a dot
        if not cleaned.startswith("."):
            cleaned = f".{cleaned}"

        return cleaned

    def _generate_temp_filename(self) -> str:
        """Generate a temporary filename.

        Returns:
            The temporary filename or absolute path as a string, or error message
        """
        # Get input values
        directory = self.get_parameter_value("directory")
        extension = self.get_parameter_value("extension")
        suffix = self.get_parameter_value("suffix")
        prefix = self.get_parameter_value("prefix")
        name = self.get_parameter_value("name")
        separator = self.get_parameter_value("separator")
        return_absolute_path = self.get_parameter_value("return_absolute_path")

        # Validate directory (failure case first)
        validated_dir = self._clean_and_validate_directory(directory)
        if isinstance(validated_dir, str) and validated_dir.startswith("Error:"):
            return validated_dir

        # Normalize extension and clean suffix/prefix/name/separator
        normalized_extension = self._normalize_extension(extension)
        cleaned_suffix = self._clean_string_parameter(suffix)
        cleaned_prefix = self._clean_string_parameter(prefix)
        cleaned_name = self._clean_string_parameter(name)
        cleaned_separator = self._clean_string_parameter(separator)

        # Default separator to "_" if empty
        if not cleaned_separator:
            cleaned_separator = "_"

        # Build combined prefix: prefix + separator + name + separator
        # This will result in: prefix_name_RANDOM
        combined_prefix_parts = []
        if cleaned_prefix:
            combined_prefix_parts.append(cleaned_prefix)
        if cleaned_name:
            if combined_prefix_parts:
                combined_prefix_parts.append(cleaned_separator)
            combined_prefix_parts.append(cleaned_name)
        # Always add separator at the end to separate from random part
        if combined_prefix_parts:
            combined_prefix_parts.append(cleaned_separator)
        combined_prefix = "".join(combined_prefix_parts)

        # Combine suffix and extension (suffix first, then extension)
        # This will result in: RANDOM_suffix.ext
        combined_suffix = cleaned_suffix + normalized_extension

        # Generate temporary filename using mkstemp (creates file, returns fd and path)
        temp_path_obj: Path | None = None
        try:
            fd, temp_path = tempfile.mkstemp(suffix=combined_suffix, prefix=combined_prefix, dir=validated_dir)
            # Close the file descriptor immediately (we just want the filename)
            os.close(fd)
            # Convert to Path for easier manipulation
            temp_path_obj = Path(temp_path)
            # Delete the file since we only want the filename
            temp_path_obj.unlink()
        except OSError as e:
            return f"Error: {self.name} - Failed to generate temporary filename: {e}"

        # Return absolute path or just filename based on setting (success path at end)
        if temp_path_obj is None:
            return f"Error: {self.name} - Failed to generate temporary filename"

        if return_absolute_path:
            result = str(temp_path_obj.resolve())
        else:
            result = temp_path_obj.name

        return result

    def after_value_set(self, parameter: Parameter, value: Any) -> None:
        if parameter.name in (
            "directory",
            "extension",
            "suffix",
            "prefix",
            "name",
            "separator",
            "return_absolute_path",
        ):
            self._update_output()
        return super().after_value_set(parameter, value)

    def _update_output(self) -> None:
        """Update the output parameter with the generated temp filename."""
        temp_filename = self._generate_temp_filename()

        # Set the output value
        self.set_parameter_value("filename", temp_filename)
        self.publish_update_to_parameter("filename", temp_filename)
        self.parameter_output_values["filename"] = temp_filename

    def after_incoming_connection(
        self,
        source_node: BaseNode,
        source_parameter: Parameter,
        target_parameter: Parameter,
    ) -> None:
        pass

    def process(self) -> None:
        """Generate and set the temporary filename."""
        self._update_output()
